--
-- Script was generated by Devart dbForge Studio for MySQL, Version 9.2.105.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2024. 09. 24. 8:36:04
-- Server version: 8.4.0
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8mb4';

--
-- Set default database
--
USE kocsi_adatbazis;

--
-- Drop table `auto`
--
DROP TABLE IF EXISTS auto;

--
-- Drop table `elado`
--
DROP TABLE IF EXISTS elado;

--
-- Drop table `marka_azonosito`
--
DROP TABLE IF EXISTS marka_azonosito;

--
-- Drop table `modell_azonosito`
--
DROP TABLE IF EXISTS modell_azonosito;

--
-- Drop table `szin_azonosito`
--
DROP TABLE IF EXISTS szin_azonosito;

--
-- Set default database
--
USE kocsi_adatbazis;

--
-- Create table `szin_azonosito`
--
CREATE TABLE szin_azonosito (
  `Szín azonosító` INT DEFAULT NULL,
  Szín VARCHAR(50) DEFAULT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1638,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `modell_azonosito`
--
CREATE TABLE modell_azonosito (
  `Modell azonosító` INT DEFAULT NULL,
  `Márka azonosító` INT DEFAULT NULL,
  Modell VARCHAR(50) DEFAULT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1092,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `marka_azonosito`
--
CREATE TABLE marka_azonosito (
  `Márka azonosító` INT DEFAULT NULL,
  Márka VARCHAR(50) DEFAULT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `elado`
--
CREATE TABLE elado (
  Azonosító INT DEFAULT NULL,
  Név VARCHAR(50) DEFAULT NULL,
  Telefonszám VARCHAR(50) DEFAULT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 819,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `auto`
--
CREATE TABLE auto (
  Azonosító INT DEFAULT NULL,
  Rendszám VARCHAR(50) DEFAULT NULL,
  Ár INT DEFAULT NULL,
  `Szín azonosító` INT DEFAULT NULL,
  `Modell azonosító` INT DEFAULT NULL,
  Telefonszám INT DEFAULT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 327,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

-- 
-- Dumping data for table szin_azonosito
--
INSERT INTO szin_azonosito VALUES
(1, 'Fekete'),
(2, 'Fehér'),
(3, 'Piros'),
(4, 'Kék'),
(5, 'Szürke'),
(6, 'Zöld'),
(7, 'Sárga'),
(8, 'Narancs'),
(9, 'Lila'),
(10, 'Barna');

-- 
-- Dumping data for table modell_azonosito
--
INSERT INTO modell_azonosito VALUES
(1, 1, 'Corolla'),
(2, 1, 'Camry'),
(3, 1, 'Yaris'),
(4, 2, 'Focus'),
(5, 2, 'Fiesta'),
(6, 2, 'Mustang'),
(7, 3, 'Golf'),
(8, 3, 'Passat'),
(9, 3, 'Polo'),
(10, 4, '3 Series'),
(11, 4, '5 Series'),
(12, 4, 'X5'),
(13, 5, 'A4'),
(14, 5, 'Q5'),
(15, 5, 'A3');

-- 
-- Dumping data for table marka_azonosito
--
INSERT INTO marka_azonosito VALUES
(1, 'Toyota'),
(2, 'Ford'),
(3, 'Volkswagen'),
(4, 'BMW'),
(5, 'Audi');

-- 
-- Dumping data for table elado
--
INSERT INTO elado VALUES
(1, 'Nagy László', '06213669395'),
(2, 'Kovács Péter', '06864603607'),
(3, 'Szabó Anna', '06500684373'),
(4, 'Tóth Gábor', '06252790298'),
(5, 'Kiss János', '06082420578'),
(6, 'Farkas Ilona', '06622448532'),
(7, 'Németh Erika', '06132370184'),
(8, 'Molnár Tibor', '06507836073'),
(9, 'Lakatos Tamás', '06467106358'),
(10, 'Balogh Zsolt', '06706899553'),
(11, 'Szilágyi Judit', '06354501041'),
(12, 'Horváth Béla', '06591686709'),
(13, 'Varga Krisztián', '06345751248'),
(14, 'Kocsis Éva', '06967763739'),
(15, 'Nagy István', '06673138917'),
(16, 'Szalai Mária', '06200924931'),
(17, 'Bíró Attila', '06676732214'),
(18, 'Váradi Balázs', '06595099711'),
(19, 'Mészáros Andrea', '06668130124'),
(20, 'Pintér Katalin', '06182112233');

-- 
-- Dumping data for table auto
--
INSERT INTO auto VALUES
(1, 'FYIR-364', 4491895, 5, 14, 11),
(2, 'JHCF-537', 1481750, 1, 1, 19),
(3, 'HEHB-829', 2691795, 3, 11, 11),
(4, 'VKLU-911', 2621345, 6, 11, 9),
(5, 'MVWZ-060', 1718396, 4, 15, 20),
(6, 'KFMF-121', 1943914, 9, 11, 18),
(7, 'PDJQ-696', 1334384, 2, 12, 1),
(8, 'EWGX-922', 3866950, 2, 14, 4),
(9, 'UVLK-559', 2867224, 5, 6, 16),
(10, 'WDEX-846', 4974402, 9, 15, 7),
(11, 'HTQW-475', 4124527, 5, 2, 2),
(12, 'LTHZ-245', 2950724, 2, 15, 7),
(13, 'HNOZ-848', 2019883, 8, 6, 5),
(14, 'CHDA-082', 1807345, 4, 7, 19),
(15, 'CRGU-074', 2933606, 2, 11, 8),
(16, 'DUHX-839', 3400955, 3, 6, 14),
(17, 'OORS-599', 1977098, 4, 11, 7),
(18, 'AZHB-216', 2722029, 7, 1, 8),
(19, 'GIGQ-008', 2081361, 6, 11, 10),
(20, 'KYLQ-116', 1495468, 6, 9, 4),
(21, 'CJTY-193', 3265771, 4, 2, 15),
(22, 'CBAW-464', 2202933, 4, 2, 11),
(23, 'UERW-421', 1972031, 2, 10, 10),
(24, 'EGUO-670', 3066595, 6, 11, 10),
(25, 'VNEE-339', 3368794, 5, 6, 10),
(26, 'BEBV-297', 2667227, 2, 13, 3),
(27, 'TIZQ-536', 2477579, 1, 9, 13),
(28, 'IQFG-118', 2261969, 4, 4, 14),
(29, 'QQDZ-381', 3379750, 2, 2, 10),
(30, 'IIYX-088', 4256713, 1, 7, 6),
(31, 'WSLE-383', 2133818, 5, 4, 12),
(32, 'VHCQ-697', 4037852, 7, 14, 20),
(33, 'ZPHV-732', 1615938, 7, 8, 19),
(34, 'ZIDC-372', 3089760, 2, 10, 19),
(35, 'HHRV-549', 3941457, 3, 2, 20),
(36, 'YVCH-833', 3349072, 3, 13, 1),
(37, 'LULI-042', 2387525, 9, 12, 17),
(38, 'JCZP-599', 2179062, 6, 11, 4),
(39, 'HDLY-710', 3411960, 1, 4, 6),
(40, 'PTBF-098', 2346199, 7, 2, 12),
(41, 'RVLH-330', 4965052, 10, 7, 2),
(42, 'IMGA-165', 3460845, 9, 14, 14),
(43, 'AYWG-694', 2838360, 3, 9, 2),
(44, 'WWXN-302', 2668082, 10, 2, 16),
(45, 'IEWK-278', 1581008, 4, 1, 3),
(46, 'DRYC-624', 4817303, 2, 7, 18),
(47, 'IIPB-496', 4861085, 1, 7, 20),
(48, 'JGHY-578', 4045069, 5, 13, 18),
(49, 'VTZS-548', 1631919, 6, 10, 18),
(50, 'HQDX-963', 2878806, 3, 8, 1);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;